  name: CI
  on: [push]

  jobs:
      test:
          runs-on: ubuntu-latest
          steps:
              - name: Checkout code
                uses: actions/checkout@v2
              - name: Setup Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: 18.14.12
              - name: Install dependencies
                run: npm install
              - name: Run tests
                run: npm run test:cov
              - name: SonarCloud Scan
                uses: sonarsource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}